name: Test Workflow
on: 
  workflow_dispatch
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: list tags
        uses: actions/github-script@v5
        continue-on-error: true
        id: list_tags
        env:
          VERSION: '${{secrets.VERSION}}'
        with:
          script: |
            const { VERSION } = process.env
            const output = await(github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "sometag"
            }))
            console.log(output)
            if (output.status == "404") {
              const { VERSION } = "sometag"
              console.log("not found, create tag")
              git config --global user.email "me@example.com"
              git config --global user.name "tagairosin"
              git tag -a `${VERSION}` -m "tagging for release"
              git push origin `${VERSION}`
              console.log("create draft release")
              github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: `${VERSION}`,
                name: "Test Release Draft",
                draft: true,
                body: "this is an test tag release draft etc."
              })
            }
            
