name: Test Workflow
on: 
  workflow_dispatch
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: list tags
        uses: actions/github-script@v5
        continue-on-error: true
        id: list_tags
        env:
          VERSION: '${{secrets.VERSION}}'
        with:
          script: |
            const { VERSION } = process.env
            var output
            try {
              output = await(github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: "sometag"
              }))
              console.log(output)
              # github.rest.repos.createRelease({
              #   owner: context.repo.owner,
              #   repo: context.repo.repo,
              #   tag_name: `${VERSION}`,
              #   name: "Test Release Draft",
              #   draft: true,
              #   body: "this is an test tag release draft etc."
              # })
            }
            catch (error) {
              console.log(error)
              if (error.status == "404") {
                console.log("tag not found, create draft release")
                github.rest.repos.createRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: "sometag",
                  name: "Test Release Draft",
                  draft: true,
                  body: "this is a sometag release draft etc."
                })
              }
            }
            return output
      - name: next step
        run: |
          echo "past next steps"
          echo "${{steps.list_tags.outputs.result}}"          
