name: Test Workflow
env:
  VERSION: ${{ secrets.VERSION }}
on: 
  workflow_dispatch
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: create draft release
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRelease({
              tag_name: $VERSION,
              name: "Test Release Draft",
              draft: true,
              body: "this is a test tag release draft etc."
            })
