name: Test Workflow
on: 
  workflow_dispatch
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: list tags
        uses: actions/github-script@v5
        continue-on-error: true
        id: list_tags
        env:
          VERSION: '${{secrets.VERSION}}'
        with:
          script: |
            const { VERSION } = process.env
            # try {
            #   const output = await(github.rest.repos.getReleaseByTag({
            #     owner: context.repo.owner,
            #     repo: context.repo.repo,
            #     tag_name: "sometag"
            #   }))
            # }
            # catch (error) {
            #   console.log(error)
            # }
            return github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: "sometag"
              })
      - name: next step
        run: |
          echo "past next steps"
          echo "${{steps.list_tags.outputs.result}}"          
