name: Test Workflow
on: 
  workflow_dispatch
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: list tags
        uses: actions/github-script@v5
        id: list_tags
        env:
          VERSION: '${{secrets.VERSION}}'
        with:
          script: |
            github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            console.log("after getreleasebytag")
            console.log(`"${{steps.list_tags.outputs.result}}"`)
      - name: steps result
        run: echo "${{steps.list_tags.outputs.result}}"
#       - name: Tag repo
#         run: |
#           git config --global user.email "me@example.com"
#           git config --global user.name "tagairosin"
#           git tag -a ${{ secrets.VERSION }} -m "tagging for release"
#           git push origin ${{ secrets.VERSION }}
#       - name: create draft release
#         uses: actions/github-script@v5
#         id: this_id
#         env:
#           VERSION: '${{secrets.VERSION}}'
#         with:
#           script: |
#             github.rest.repos.getReleaseByTag({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               tag_name: "sometag"
#             })
#             echo "after getreleasebytag"
#             echo "${{steps.this_id.outputs.result}}"
#             const { VERSION } = process.env
#             github.rest.repos.createRelease({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               tag_name: `${VERSION}`,
#               name: "Test Release Draft",
#               draft: true,
#               body: "this is a test tag release draft etc."
#             })
#             echo "aftercreaterelease"
#             echo "${{steps.this_id.outputs.result}}"
#       - name: steps result
#         run: echo "${{steps.this_id.outputs.result}}"
