name: Test Workflow
on: 
  workflow_dispatch
env:   
  VERSION: ${{ secrets.VERSION }}
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: list tags
        uses: actions/github-script@v5
        continue-on-error: true
        id: list_tags
        env:
          VERSION: '${{secrets.VERSION}}'
        with:
          script: |
            github.rest.repos.listTags({
                owner: context.repo.owner,
                repo: context.repo.repo
              })
