name: Test Workflow
on: 
  workflow_dispatch
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag repo
        run: |
          git config --global user.email "me@example.com"
          git config --global user.name "tagairosin"
          git tag -a ${{ secrets.VERSION }} -m "tagging for release"
      - name: create draft release
        uses: actions/github-script@v5
        env:
          VERSION: '${{secrets.VERSION}}'
        with:
          script: |
            const { VERSION } = process.env
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `${VERSION}`,
              name: "Test Release Draft",
              draft: true,
              body: "this is a test tag release draft etc."
            })
