name: Test Workflow
on: 
  workflow_dispatch
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: list tags
        uses: actions/github-script@v5
        continue-on-error: true
        id: list_tags
        env:
         VERSION: '${{ secrets.VERSION }}'
        with:
          script: |
            const { VERSION } = process.env
            console.log(`${VERSION}`)
            var found = false
            const output = await(github.rest.repos.listTags({
                owner: context.repo.owner,
                repo: context.repo.repo
              }))
            console.log(output.data)
            for (const tag of output.data) {
              console.log(tag.name)
              if (tag.name == `${VERSION}`) {
                found = true
                console.log("found tag")
              }
            }
            return found
