name: Test Workflow
on: 
  workflow_dispatch
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: create draft release
        uses: actions/github-script@v5
        env:
          VERSION: '${{secrets.VERSION}}'
        with:
          script: |
            const { VERSION } = process.env
            github.rest.git.createRelease({
              tag_name: `${VERSION}`,
              name: "Test Release Draft",
              draft: true,
              body: "this is a test tag release draft etc."
            })
