name: Test Workflow
on: 
  workflow_dispatch
env:   
  VERSION: ${{ secrets.VERSION }}
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: list tags
        uses: actions/github-script@v5
        continue-on-error: true
        id: list_tags
        env:
          VERSION: '${{secrets.VERSION}}'
        with:
          script: |
            const { VERSION } = process.env
            var retval = false
            try {
              const output = await(github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: `${VERSION}`
              }))
              console.log(output)
            }
            catch (error) {
              console.log(error)
              if (error.status == "404") {
                console.log("not found")
                retval = true
              }
            }
            return retval
      - name: Check out repo
        if: ${{steps.list_tags.outputs.result}}
        uses: actions/checkout@v2
      - name: create tag
        id: create_tag
        # last step was failure = release tag wasn't found
        if: ${{steps.list_tags.outputs.result}}
        run: |
          echo ${{steps.list_tags.outputs.result}}
          git config --global user.email "me@example.com"
          git config --global user.name "tagairosin"
          git tag -a ${VERSION} -m "tagging for release"
          git push origin ${VERSION}
          echo "tag created"
      - name: draft release
        if: ${{steps.list_tags.outputs.result}}
        uses: actions/github-script@v5
        id: draft_release
        env:
          VERSION: '${{secrets.VERSION}}'
        with:
          script: |
            const { VERSION } = process.env
            github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: `${VERSION}`,
                name: "Test Release",
                draft: true,
                body: "this is a test tag release draft etc."
              })
