name: Shiny New Workflow
env:
  VERSION: ${{ secrets.VERSION }}
  BRANCH: master
on: 
  workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    name: test stuff
    steps:
      - name: run script
        if: ${{github.ref_name == env.BRANCH}}
        run: |
          echo "it frickin worked"
