name: Shiny New Workflow
env:
  VERSION: ${{ secrets.VERSION }}
  BRANCH: master
on: 
  workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    name: test stuff
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: run script
        run: |
          cd .github/workflows
          python post_stuff.py
