name: Shiny New Workflow
env:
  VERSION: ${{ secrets.VERSION }}
on: 
  workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    name: test stuff
    steps:
      - name: Install required system packages
        run: |
          pip install PyGithub requests
      - name: Checkout
        uses: actions/checkout@v2
      - name: run script
        run: |
          cd .github/workflows
          python post_stuff.py
