name: Shiny New Workflow
env:
  VERSION: ${{ secrets.VERSION }}
  BRANCH: master
on: 
  workflow_dispatch
jobs:
  create-update-tag-release:
    name: Create or update tag and release draft
    runs-on: ubuntu-latest
    steps:
      - name: Check Tags
        uses: actions/github-script@v5
        continue-on-error: true
        id: check_tags
        with:
          script: |
            const { VERSION } = process.env
            var found = true
            try {
              var output = await (github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${VERSION}`
              }))
            }
            catch {
              found = false
            }  
            return found
      - name: Update Release Draft
        id: update_draft
        if: ${{steps.check_tags.outputs.result == 'true'}}
        uses: actions/github-script@v5
        with:
          script: |
            const { VERSION } = process.env
            var updated = false
            const releases = await(github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            }))
            console.log(releases)
            for (const rel of releases.data) {
              console.log(rel.id)
              console.log(rel.draft)
              if (rel.tag_name == `${VERSION}` && rel.draft === true) {
                console.log("matched tag")
                github.rest.repos.updateRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: `${VERSION}`,
                  release_id: rel.id,
                  name: `${VERSION}`,
                  draft: true
                })
                updated = true
                break
              }
            }
            return updated
